// Branch naming, push, PR creation via gh CLI

import { spawnSync } from "node:child_process";
import { log } from "../logger.ts";
import type { LinearIssue } from "../types.ts";

/**
 * Check if there are commits on the branch beyond the base
 */
export function hasCommits(worktreePath: string, defaultBranch: string): boolean {
  try {
    const result = spawnSync(
      "git",
      ["log", `origin/${defaultBranch}..HEAD`, "--oneline"],
      {
        cwd: worktreePath,
        timeout: 10_000,
        encoding: "utf-8",
      }
    );
    if (result.status !== 0) return false;
    return result.stdout.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * Push the branch to origin (runner does this, not the agent)
 */
export function pushBranch(worktreePath: string, branch: string, issueId: string): void {
  const result = spawnSync("git", ["push", "-u", "origin", branch], {
    cwd: worktreePath,
    timeout: 60_000,
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    throw new Error(`git push failed: ${result.stderr}`);
  }
  log("OK", issueId, `Pushed branch ${branch}`);
}

/**
 * Create a PR via gh CLI
 */
export function createPR(
  worktreePath: string,
  issue: LinearIssue,
  labels: string[],
  defaultBranch: string
): string {
  const title = `${issue.identifier}: ${issue.title}`;
  const body = [
    `## Linear Issue`,
    `[${issue.identifier}: ${issue.title}](${issue.url})`,
    "",
    issue.description ? `## Description\n${issue.description}` : "",
    "",
    "---",
    `Generated by task-runner from ${issue.identifier}`,
  ]
    .filter(Boolean)
    .join("\n");

  const args = ["pr", "create", "--title", title, "--body", body, "--base", defaultBranch];
  for (const label of labels) {
    args.push("--label", label);
  }

  const result = spawnSync("gh", args, {
    cwd: worktreePath,
    timeout: 30_000,
    encoding: "utf-8",
  });

  if (result.status !== 0) {
    throw new Error(`gh pr create failed: ${result.stderr}`);
  }

  const prUrl = result.stdout.trim();
  log("OK", issue.identifier, `Created PR: ${prUrl}`);
  return prUrl;
}

/**
 * Add a label to a PR
 */
export function addPRLabel(prUrl: string, label: string): void {
  const result = spawnSync("gh", ["pr", "edit", prUrl, "--add-label", label], {
    timeout: 15_000,
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    throw new Error(`gh pr edit failed: ${result.stderr}`);
  }
}

/**
 * Add a comment to a PR
 */
export function addPRComment(prUrl: string, body: string): void {
  const result = spawnSync("gh", ["pr", "comment", prUrl, "--body", body], {
    timeout: 15_000,
    encoding: "utf-8",
  });
  if (result.status !== 0) {
    throw new Error(`gh pr comment failed: ${result.stderr}`);
  }
}
