// Branch naming, push, PR creation via gh CLI

import { log } from "../logger.ts";
import { execGit, execGh, validateBranchName } from "./exec.ts";
import type { LinearIssue } from "../types.ts";

/**
 * Check if there are commits on the branch beyond the base
 */
export function hasCommits(worktreePath: string, defaultBranch: string): boolean {
  try {
    validateBranchName(defaultBranch);
    const result = execGit(
      ["log", `origin/${defaultBranch}..HEAD`, "--oneline"],
      { cwd: worktreePath, timeout: 10_000 }
    );
    return result.length > 0;
  } catch {
    return false;
  }
}

/**
 * Push the branch to origin (runner does this, not the agent)
 */
export function pushBranch(worktreePath: string, branch: string, issueId: string): void {
  validateBranchName(branch);
  execGit(["push", "-u", "origin", branch], {
    cwd: worktreePath,
    timeout: 60_000,
  });
  log("OK", issueId, `Pushed branch ${branch}`);
}

/**
 * Create a PR via gh CLI
 */
export function createPR(
  worktreePath: string,
  issue: LinearIssue,
  labels: string[],
  defaultBranch: string
): string {
  validateBranchName(defaultBranch);

  const title = `${issue.identifier}: ${issue.title}`;
  const body = [
    `## Linear Issue`,
    `[${issue.identifier}: ${issue.title}](${issue.url})`,
    "",
    issue.description ? `## Description\n${issue.description}` : "",
    "",
    "---",
    `Generated by task-runner from ${issue.identifier}`,
  ]
    .filter(Boolean)
    .join("\n");

  const args = [
    "pr", "create",
    "--title", title,
    "--body", body,
    "--base", defaultBranch,
  ];
  if (labels.length > 0) {
    args.push("--label", labels.join(","));
  }

  const result = execGh(args, { cwd: worktreePath, timeout: 30_000 });
  const prUrl = result.trim();
  log("OK", issue.identifier, `Created PR: ${prUrl}`);
  return prUrl;
}

/**
 * Add a label to a PR
 */
export function addPRLabel(prUrl: string, label: string): void {
  execGh(["pr", "edit", prUrl, "--add-label", label], { timeout: 15_000 });
}

/**
 * Add a comment to a PR
 */
export function addPRComment(prUrl: string, body: string): void {
  execGh(["pr", "comment", prUrl, "--body", body], { timeout: 15_000 });
}
