// Branch naming, push, PR creation via gh CLI

import { execSync } from "node:child_process";
import { log } from "../logger.ts";
import type { LinearIssue } from "../types.ts";

/**
 * Check if there are commits on the branch beyond the base
 */
export function hasCommits(worktreePath: string, defaultBranch: string): boolean {
  try {
    const result = execSync(
      `git log "origin/${defaultBranch}..HEAD" --oneline`,
      {
        cwd: worktreePath,
        timeout: 10_000,
        encoding: "utf-8",
      }
    );
    return result.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * Push the branch to origin (runner does this, not the agent)
 */
export function pushBranch(worktreePath: string, branch: string, issueId: string): void {
  execSync(`git push -u origin "${branch}"`, {
    cwd: worktreePath,
    timeout: 60_000,
    encoding: "utf-8",
  });
  log("OK", issueId, `Pushed branch ${branch}`);
}

/**
 * Create a PR via gh CLI
 */
export function createPR(
  worktreePath: string,
  issue: LinearIssue,
  labels: string[],
  defaultBranch: string
): string {
  const title = `${issue.identifier}: ${issue.title}`;
  const body = [
    `## Linear Issue`,
    `[${issue.identifier}: ${issue.title}](${issue.url})`,
    "",
    issue.description ? `## Description\n${issue.description}` : "",
    "",
    "---",
    `Generated by task-runner from ${issue.identifier}`,
  ]
    .filter(Boolean)
    .join("\n");

  const labelArgs = labels.length > 0 ? `--label "${labels.join(",")}"` : "";

  const result = execSync(
    `gh pr create --title "${escapeShell(title)}" --body "${escapeShell(body)}" --base "${defaultBranch}" ${labelArgs}`,
    {
      cwd: worktreePath,
      timeout: 30_000,
      encoding: "utf-8",
    }
  );

  const prUrl = result.trim();
  log("OK", issue.identifier, `Created PR: ${prUrl}`);
  return prUrl;
}

/**
 * Add a label to a PR
 */
export function addPRLabel(prUrl: string, label: string): void {
  execSync(`gh pr edit "${prUrl}" --add-label "${label}"`, {
    timeout: 15_000,
    encoding: "utf-8",
  });
}

/**
 * Add a comment to a PR
 */
export function addPRComment(prUrl: string, body: string): void {
  execSync(`gh pr comment "${prUrl}" --body "${escapeShell(body)}"`, {
    timeout: 15_000,
    encoding: "utf-8",
  });
}

function escapeShell(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/`/g, "\\`");
}
