// Prompt template for review agents

import type { LinearIssue, ProjectConfig } from "../types.ts";

export function buildReviewPrompt(
  issue: LinearIssue,
  teamConfig: ProjectConfig,
  prUrl: string
): string {
  return `You are reviewing a pull request generated by an AI agent. Be thorough but fair.

## Context

**Ticket: ${issue.identifier}: ${issue.title}**

Description:
${issue.description ?? "No description provided."}

PR URL: ${prUrl}

## Review Process

1. Read the PR diff using \`gh pr diff "${prUrl}"\` or \`git diff origin/main...HEAD\`.
2. Read the full content of any modified files to understand context.
3. Run the test suite: \`${teamConfig.testCommand}\`
4. Run the linter: \`${teamConfig.lintCommand}\`
${teamConfig.buildCommand ? `5. Run the build: \`${teamConfig.buildCommand}\`` : ""}
5. Evaluate the changes against the ticket requirements.

## Evaluation Criteria

- **Correctness:** Does the code do what the ticket asks?
- **Tests:** Are there adequate tests? Do they pass?
- **Code quality:** Does it follow project conventions? Is it clean and maintainable?
- **Security:** No obvious vulnerabilities (injection, XSS, etc.)?
- **Scope:** Are changes minimal and focused on the ticket?

## Output Format

You MUST output ONLY a JSON object with this exact schema (no other text before or after):

\`\`\`json
{
  "approved": true | false,
  "summary": "One-paragraph summary of the review.",
  "issues": [
    {
      "severity": "critical" | "major" | "minor" | "nit",
      "file": "path/to/file.ts",
      "description": "Description of the issue."
    }
  ],
  "testsPass": true | false,
  "lintPass": true | false,
  "tscPass": true | false
}
\`\`\`

## Approval Criteria

Approve if ALL of:
- Tests pass
- Lint passes
- TypeScript compiles (if applicable)
- No critical issues
- At most 2 major issues

Reject if ANY of:
- Tests fail
- Critical issues found
- More than 2 major issues
- Changes don't address the ticket requirements`;
}
